spring:
  datasource:
    # 替换为你图片中的 Railway 公共网络 Host、端口和数据库名 (railway)
    url: jdbc:mysql://caboose.proxy.rlwy.net:11100/railway?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    # 替换为 Railway 提供的用户名
    username: root
    # 替换为你命令里的真实密码
    password: NAgBuOGRzIuDXKSyjIjmRPDQujwIfHaZ
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:5173
      - https://junyuc.me
      - https://www.junyuc.me
      - https://esp32-final-2zz8qglef-qregrets-projects.vercel.app # 把现在的预览地址加上

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  # 关键修改：云平台通常通过环境变量 PORT 来动态分配端口。
  # 这里的语法是：优先使用系统的 PORT 变量，如果没有（比如你在本地运行），就默认用 8080。
  port: ${PORT:8080}
